### ISSUE TITLE
Multiple Gerrit servers support

### ISSUE THREAD

**Issue by wildy** [MeetMe/jira-gerrit-plugin#40] opened 2016-12-21 15:02 UTC
Hi.

It's really sad that the plugin currently can only support one Gerrit server. Please consider adding multiple servers support soon - for example in my case, there are two departments using two Gerrit servers on the intranet but JIRA is common to the company.

**Comment by jhansche** [comment] 2017-02-02 20:28
Duplicate of #2

**Closed by jhansche** 2017-02-02 20:28 UTC
Labels: duplicate
