### ISSUE TITLE
Commit-Issue relations breaks when Issue is moved to another JIRA project

### ISSUE THREAD

**Issue by bfrauen** [MeetMe/jira-gerrit-plugin#36] opened 2016-07-22 10:46 UTC
Hi Joe Hansche,

we have the problem that the commit-Issue relations breaks when we move issues to another JIRA project. JIRA keeps the former keys of issues in a separate table so your add-on should be lookup these values to keep the connection.

Best Björn

Please contact me on skype (bjoern.frauen) or email (bfrauen@stagil.de) for any questions.

**Comment by jhansche** [comment] 2016-09-06 17:36
This is a duplicate of #25.

That issue was addressed in PR #33, which was just included in the 3.1 release of the plugin:
https://marketplace.atlassian.com/plugins/com.meetme.plugins.jira.gerrit-plugin/versions#b57

**Closed by jhansche** 2016-09-06 17:36 UTC
Labels: duplicate
